language: java

jdk:
  - oraclejdk8

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - mysql -e 'create database travis_ci_test;' -u root

script:
  - "./gradlew check --info"
  - "./gradlew integrationTest"

sudo: false