language: java
jdk:
- oraclejdk8
services:
  - postgresql
  - mysql
  - mongodb
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- psql -c 'create schema j_some authorization postgres;' -U postgres travis_ci_test
- mysql -e 'create database travis_ci_test;' -u root
- mongo mydb_test --eval 'db.createUser("travis", "test");'
script:
- ./gradlew build
- ./gradlew integrationTest
deploy:
  skip_cleanup: true
  provider: script
  script: travis/deployToSonatype.sh
  on:
    tags: true
    all_branches: true
sudo: false

