language: java

jdk:
  - oraclejdk8

addons:
  apt:
    sources:
      - mongodb-upstart
      - mongodb-3.2-precise
    packages:
      - mongodb-org-server
      - mongodb-org-shell

before_script:
  - sleep 15 #mongo may not be responded directly
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql -c 'create schema j_some authorization postgres;' -U postgres travis_ci_test
  - mysql -e 'create database travis_ci_test;' -u root

script:
  - "./gradlew check"
  - "./gradlew integrationTest"

deploy:
  provider: script
  script:
  - "./gradlew uploadArchives -PnexusUsername=$sonatypeUser -PnexusPassword=$sonatypePassword"
  - "./gradlew closeAndPromoteRepository -PnexusUsername=$sonatypeUser -PnexusPassword=$sonatypePassword"
  on:
    tags: true
    all_branches: true

sudo: false